### ISSUE TITLE
Missing Vertical Separator Style

### ISSUE THREAD

**Issue by fgnm** [kotcrab/vis-ui#325]
In a very old `VisTable` it was possible to set custom style between horizontal and vertical `Separator`: [L46](https://github.com/kotcrab/vis-ui/blob/19dc256df8df82465e0927f5f22ac7f194124156/UI/src/com/kotcrab/vis/ui/widget/VisTable.java#L46)

Is it possible to add this feature again? Maybe this [line](https://github.com/kotcrab/vis-ui/blob/a79ace7103c96b97317e596f0729996d7a9cccb1/ui/src/main/java/com/kotcrab/vis/ui/widget/VisTable.java#L46) could be edit in this way:

```Java
Cell<Separator> cell = add(new Separator(vertical ? "vertical" : "default")).padTop(2).padBottom(2);
```

Is there any particular reason why it was removed?
Thanks

**Comment by kotcrab** [comment]
According to the change log this was removed in VisUI 1.0.0. The reason was "it's not used". If you look at the [Separator](https://github.com/kotcrab/vis-ui/blob/19dc256df8df82465e0927f5f22ac7f194124156/UI/src/com/kotcrab/vis/ui/widget/Separator.java) implementation at that time the `vertical` property of the `SeparatorStyle` is not used anywhere. The `vertical` property set to true was the only difference between the `"vertical"` and `"default"` styles. How separator looks in a table (vertical or horizontal) depends on the cell sizing and not on this `vertical` property.

What's your intent of using this? Do you want to use different style (`background`, `thickness`) for the vertical/horizontal separator?

**Comment by fgnm** [comment]
Yes, the idea is to control different thickness and background between vertical and horizontal `Separator`, as it happens for [`PopupMenu`](https://github.com/kotcrab/vis-ui/blob/3412fb9f60422052dca776df9fbc825b90dd860e/ui/src/main/java/com/kotcrab/vis/ui/widget/PopupMenu.java#L241).

```
com.kotcrab.vis.ui.widget.Separator$SeparatorStyle: {
    default: {
      background: separator,
      thickness: 2
    },
    vertical: {
      background: separator-vertical,
      thickness: 3,
    },
    menu: {
      background: separator-menu,
      thickness: 2
    }
  }
```

I've made it in a custom `VisTable` class that override `addSeparator`, anyway it might be useful to include by default.

```JAVA
    @Override
    public Cell<Separator> addSeparator (boolean vertical) {
        Cell<Separator> cell = add(new Separator(vertical ? "vertical" : "default")).padTop(2).padBottom(2);

        if (vertical)
            cell.fillY().expandY();
        else {
            cell.fillX().expandX();
            row();
        }

        return cell;
    }
```

**Comment by kotcrab** [comment]
I guess it can be added, this would also require adding back the `vertical` style to avoid breaking change.
