### ISSUE TITLE
VisImageButton getImage().setColor(color) does not work.

### ISSUE THREAD

**Issue by unenergizer** [kotcrab/vis-ui#355]
As stated in the title, when I do `visImageButton.getImage().setColor(Color.RED);` Nothing happens. I can set a color to the background but that is about it. However, if I do the same thing using a regular ImageButton, it works just fine.

**Comment by czyzby** [comment]
It's likely due to [these lines](https://github.com/kotcrab/vis-ui/blob/master/ui/src/main/java/com/kotcrab/vis/ui/widget/VisImageButton.java#L135-L138):

```java
		if (generateDisabledImage && style.imageDisabled == null && isDisabled())
			image.setColor(Color.GRAY);
		else
			image.setColor(Color.WHITE);
```

The color is overridden to support the automatic disabled icon generation. I think the `generateDisabledImage` check should be extracted before this whole code block to avoid changing the color if this feature is not enabled:

```java
	if (generateDisabledImage) {
		if (style.imageDisabled == null && isDisabled())
			image.setColor(Color.GRAY);
		else
			image.setColor(Color.WHITE);
	}
```

@unenergizer Would you like to test this and submit a pull request?

**Comment by unenergizer** [comment]
@czyzby I can confirm that this does indeed work. I copied the entire `VisImageButton` class into a new one, made some changes to the skin and wala it worked! However I would love to do a pull request, but I don't actually know how to do that. I only know how to submit code to my own projects default branch. Sorry!

**Comment by czyzby** [comment]
@unenergizer

> However I would love to do a pull request, but I don't actually know how to do that.

You have to make a fork of the library (top right icon), make the required changes in code and click on the pull request button. [See this article for more details.](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork)

**Comment by kotcrab** [comment]
Thank you both, I've fixed it.
